Ultimately, we want a dataframe which will have instances of teams during different seasons, and the winning percentages and salary standard deviations for every team. So each team will be represented mutliple times in this dataframe because we will include each season of the team as an instance.

In [139]:
team_wins_clean = team_wins_clean.transpose()

In [140]:
team_wins_clean

,0,1,2,3,4,5,6,7,8,9,...,63,64,65,66,67,68,69,70,71,72
Season,2021-22,2020-21,2019-20,2018-19,2017-18,2016-17,2015-16,2014-15,2013-14,2012-13,...,1958-59,1957-58,1956-57,1955-56,1954-55,1953-54,1952-53,1951-52,1950-51,1949-50
ATL,0.0,41.0,20.0,29.0,24.0,43.0,48.0,60.0,38.0,44.0,...,49.0,41.0,34.0,33.0,26.0,21.0,27.0,17.0,25.0,29.0
BOS,0,36,48,49,55,53,48,40,25,41,...,52,49,44,39,36,42,46,39,39,22
BRK,0.0,48.0,35.0,42.0,28.0,20.0,21.0,38.0,44.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHI,0.0,31.0,22.0,22.0,27.0,41.0,42.0,50.0,48.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHO,0.0,33.0,23.0,39.0,36.0,36.0,48.0,33.0,43.0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CLE,0.0,22.0,19.0,19.0,50.0,51.0,57.0,53.0,33.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAL,0.0,42.0,43.0,33.0,24.0,33.0,42.0,50.0,49.0,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEN,0.0,47.0,46.0,54.0,46.0,40.0,33.0,30.0,36.0,57.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DET,0.0,20.0,20.0,41.0,39.0,37.0,44.0,32.0,29.0,29.0,...,28.0,33.0,34.0,37.0,43.0,40.0,36.0,29.0,32.0,40.0
GSW,1,39,15,57,58,67,73,67,51,47,...,32,37,37,45,33,29,12,33,40,26
HOU,0.0,17.0,44.0,53.0,65.0,55.0,41.0,56.0,54.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IND,0.0,34.0,45.0,48.0,48.0,42.0,45.0,38.0,56.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LAC,0.0,47.0,49.0,48.0,42.0,51.0,53.0,56.0,57.0,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LAL,0.0,42.0,52.0,37.0,35.0,26.0,17.0,21.0,27.0,45.0,...,33.0,19.0,34.0,33.0,40.0,46.0,48.0,40.0,44.0,51.0
MEM,0.0,38.0,34.0,33.0,22.0,43.0,42.0,55.0,50.0,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MIA,0.0,40.0,44.0,39.0,44.0,41.0,48.0,37.0,54.0,66.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MIL,1.0,46.0,56.0,60.0,44.0,42.0,33.0,41.0,15.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MIN,0.0,23.0,19.0,36.0,47.0,31.0,29.0,16.0,40.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NOP,0.0,31.0,30.0,33.0,48.0,34.0,30.0,45.0,34.0,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NYK,0,41,21,17,29,31,32,17,37,54,...,40,35,36,35,38,44,47,37,36,40
OKC,0.0,22.0,44.0,49.0,48.0,47.0,55.0,45.0,59.0,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORL,0.0,21.0,33.0,42.0,25.0,29.0,35.0,25.0,23.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PHI,0.0,49.0,43.0,51.0,52.0,28.0,10.0,18.0,19.0,34.0,...,35.0,41.0,38.0,35.0,43.0,42.0,47.0,40.0,32.0,51.0
PHO,0.0,51.0,34.0,19.0,21.0,24.0,23.0,39.0,48.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
POR,0.0,42.0,35.0,53.0,49.0,41.0,44.0,51.0,54.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SAC,0.0,31.0,31.0,39.0,27.0,32.0,33.0,29.0,28.0,28.0,...,19.0,33.0,31.0,31.0,29.0,44.0,44.0,41.0,41.0,51.0
SAS,0.0,33.0,32.0,48.0,47.0,61.0,67.0,55.0,62.0,58.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TOR,0.0,27.0,53.0,58.0,59.0,51.0,56.0,49.0,48.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UTA,0.0,52.0,44.0,50.0,48.0,51.0,40.0,38.0,25.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WAS,0.0,34.0,25.0,32.0,43.0,49.0,41.0,46.0,44.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [141]:
#set seasons to be just the start season - since that matches with the player dataset

for i in range(team_wins_clean.shape[1]):
    team_wins_clean.loc['Season', i] = team_wins_clean.loc['Season', i].split('-')[0]
    
team_wins_clean.columns = team_wins_clean.iloc[0]

team_wins_clean = team_wins_clean.drop('Season')
team_wins_clean

Season,2021,2020,2019,2018,2017,2016,2015,2014,2013,2012,...,1958,1957,1956,1955,1954,1953,1952,1951,1950,1949
ATL,0.0,41.0,20.0,29.0,24.0,43.0,48.0,60.0,38.0,44.0,...,49.0,41.0,34.0,33.0,26.0,21.0,27.0,17.0,25.0,29.0
BOS,0,36,48,49,55,53,48,40,25,41,...,52,49,44,39,36,42,46,39,39,22
BRK,0.0,48.0,35.0,42.0,28.0,20.0,21.0,38.0,44.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHI,0.0,31.0,22.0,22.0,27.0,41.0,42.0,50.0,48.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CHO,0.0,33.0,23.0,39.0,36.0,36.0,48.0,33.0,43.0,21.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CLE,0.0,22.0,19.0,19.0,50.0,51.0,57.0,53.0,33.0,24.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DAL,0.0,42.0,43.0,33.0,24.0,33.0,42.0,50.0,49.0,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEN,0.0,47.0,46.0,54.0,46.0,40.0,33.0,30.0,36.0,57.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DET,0.0,20.0,20.0,41.0,39.0,37.0,44.0,32.0,29.0,29.0,...,28.0,33.0,34.0,37.0,43.0,40.0,36.0,29.0,32.0,40.0
GSW,1,39,15,57,58,67,73,67,51,47,...,32,37,37,45,33,29,12,33,40,26
HOU,0.0,17.0,44.0,53.0,65.0,55.0,41.0,56.0,54.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
IND,0.0,34.0,45.0,48.0,48.0,42.0,45.0,38.0,56.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LAC,0.0,47.0,49.0,48.0,42.0,51.0,53.0,56.0,57.0,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LAL,0.0,42.0,52.0,37.0,35.0,26.0,17.0,21.0,27.0,45.0,...,33.0,19.0,34.0,33.0,40.0,46.0,48.0,40.0,44.0,51.0
MEM,0.0,38.0,34.0,33.0,22.0,43.0,42.0,55.0,50.0,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MIA,0.0,40.0,44.0,39.0,44.0,41.0,48.0,37.0,54.0,66.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MIL,1.0,46.0,56.0,60.0,44.0,42.0,33.0,41.0,15.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MIN,0.0,23.0,19.0,36.0,47.0,31.0,29.0,16.0,40.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NOP,0.0,31.0,30.0,33.0,48.0,34.0,30.0,45.0,34.0,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NYK,0,41,21,17,29,31,32,17,37,54,...,40,35,36,35,38,44,47,37,36,40
OKC,0.0,22.0,44.0,49.0,48.0,47.0,55.0,45.0,59.0,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORL,0.0,21.0,33.0,42.0,25.0,29.0,35.0,25.0,23.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PHI,0.0,49.0,43.0,51.0,52.0,28.0,10.0,18.0,19.0,34.0,...,35.0,41.0,38.0,35.0,43.0,42.0,47.0,40.0,32.0,51.0
PHO,0.0,51.0,34.0,19.0,21.0,24.0,23.0,39.0,48.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
POR,0.0,42.0,35.0,53.0,49.0,41.0,44.0,51.0,54.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SAC,0.0,31.0,31.0,39.0,27.0,32.0,33.0,29.0,28.0,28.0,...,19.0,33.0,31.0,31.0,29.0,44.0,44.0,41.0,41.0,51.0
SAS,0.0,33.0,32.0,48.0,47.0,61.0,67.0,55.0,62.0,58.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TOR,0.0,27.0,53.0,58.0,59.0,51.0,56.0,49.0,48.0,34.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UTA,0.0,52.0,44.0,50.0,48.0,51.0,40.0,38.0,25.0,43.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WAS,0.0,34.0,25.0,32.0,43.0,49.0,41.0,46.0,44.0,29.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [142]:
pd.melt(team_wins_clean, id_vars=team_wins_clean.index)

KeyError: "The following 'id_vars' are not present in the DataFrame: ['ATL', 'BOS', 'BRK', 'CHI', 'CHO', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHO', 'POR', 'SAC', 'SAS', 'TOR', 'UTA', 'WAS']"

In [99]:
#convert dataframe from wide to long
team_wins_clean = team_wins_clean.reset_index()

,level_0,index,0,1,2,3,4,5,6,7,...,63,64,65,66,67,68,69,70,71,72
0,0,Season,2021,2020,2019,2018,2017,2016,2015,2014,...,1958,1957,1956,1955,1954,1953,1952,1951,1950,1949
1,1,ATL,0.0,41.0,20.0,29.0,24.0,43.0,48.0,60.0,...,49.0,41.0,34.0,33.0,26.0,21.0,27.0,17.0,25.0,29.0
2,2,BOS,0,36,48,49,55,53,48,40,...,52,49,44,39,36,42,46,39,39,22
3,3,BRK,0.0,48.0,35.0,42.0,28.0,20.0,21.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,CHI,0.0,31.0,22.0,22.0,27.0,41.0,42.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,CHO,0.0,33.0,23.0,39.0,36.0,36.0,48.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,CLE,0.0,22.0,19.0,19.0,50.0,51.0,57.0,53.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,DAL,0.0,42.0,43.0,33.0,24.0,33.0,42.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,DEN,0.0,47.0,46.0,54.0,46.0,40.0,33.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,DET,0.0,20.0,20.0,41.0,39.0,37.0,44.0,32.0,...,28.0,33.0,34.0,37.0,43.0,40.0,36.0,29.0,32.0,40.0
10,10,GSW,1,39,15,57,58,67,73,67,...,32,37,37,45,33,29,12,33,40,26
11,11,HOU,0.0,17.0,44.0,53.0,65.0,55.0,41.0,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,IND,0.0,34.0,45.0,48.0,48.0,42.0,45.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,LAC,0.0,47.0,49.0,48.0,42.0,51.0,53.0,56.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,LAL,0.0,42.0,52.0,37.0,35.0,26.0,17.0,21.0,...,33.0,19.0,34.0,33.0,40.0,46.0,48.0,40.0,44.0,51.0
15,15,MEM,0.0,38.0,34.0,33.0,22.0,43.0,42.0,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,MIA,0.0,40.0,44.0,39.0,44.0,41.0,48.0,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,MIL,1.0,46.0,56.0,60.0,44.0,42.0,33.0,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,MIN,0.0,23.0,19.0,36.0,47.0,31.0,29.0,16.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,NOP,0.0,31.0,30.0,33.0,48.0,34.0,30.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,NYK,0,41,21,17,29,31,32,17,...,40,35,36,35,38,44,47,37,36,40
21,21,OKC,0.0,22.0,44.0,49.0,48.0,47.0,55.0,45.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,ORL,0.0,21.0,33.0,42.0,25.0,29.0,35.0,25.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,PHI,0.0,49.0,43.0,51.0,52.0,28.0,10.0,18.0,...,35.0,41.0,38.0,35.0,43.0,42.0,47.0,40.0,32.0,51.0
24,24,PHO,0.0,51.0,34.0,19.0,21.0,24.0,23.0,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,POR,0.0,42.0,35.0,53.0,49.0,41.0,44.0,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,SAC,0.0,31.0,31.0,39.0,27.0,32.0,33.0,29.0,...,19.0,33.0,31.0,31.0,29.0,44.0,44.0,41.0,41.0,51.0
27,27,SAS,0.0,33.0,32.0,48.0,47.0,61.0,67.0,55.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,TOR,0.0,27.0,53.0,58.0,59.0,51.0,56.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,UTA,0.0,52.0,44.0,50.0,48.0,51.0,40.0,38.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,30,WAS,0.0,34.0,25.0,32.0,43.0,49.0,41.0,46.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pd.melt(team_wins_clean, id_vars='date', value_vars=['AA', 'BB', 'CC'])